name: KJAirdrop
main: xyz.kaijiieow.airdrop.AirdropPlugin
version: 1.0.0
api-version: '1.21'
author: Kaijiieow
description: 'Airdrop with code minigame, ownership & timers'

commands:
  airdrop:
    description: Airdrop admin command
    usage: /airdrop <reload|spawn>
    permission: airdrop.admin
    aliases: [air]

permissions:
  airdrop.admin:
    description: 'Admin permission for airdrop'
    default: op

softdepend:
  - FancyHolograms
  - MMOItems
