spawn-settings:
  enabled: true
  interval-minutes: 30
  # (แก้ตรงนี้)
  worlds:
    - "SMP"
  # (จบ)
  center-x: 0
  center-z: 0
  radius: 500
  surface-only: true

airdrop-despawn:
  enabled: true
  despawn-time-seconds: 300   # Timer A

airdrop-collect:
  collect-time-seconds: 60    # Timer B

minigame:
  code-length: 4
  damage-on-fail: 2.0
  max-attempts: 0  # 0 = ไม่จำกัด (ตอนนี้ยังไม่ได้ใช้ตัวนับ)

sounds:
  fail: BLOCK_ANVIL_LAND
  success: ENTITY_PLAYER_LEVELUP
  spawn: ENTITY_ENDER_DRAGON_GROWL
  despawn: ENTITY_GENERIC_EXPLODE

effects:
  ambient-particle: END_ROD
  ambient-interval-ticks: 10
  ambient-radius: 1.3
  beam-height: 5.0

logging:
  file-log: true
  discord-webhook-url: 'https://discord.com/api/webhooks/1438986823853408356/cDxTz7WGtvfNaVU1rWF0TcKSBHvb8da73_lHv2rIuaNGT1YXYL8fXH63320NmpFrIakz'

loot:
  default-table: 'default'